### ISSUE TITLE
[UI Upgrade]: Remove the bullets in the navbar

### ISSUE THREAD

**Issue by ketan-sonar** [pccoe-acm-hacktoberfest-2023/Starbucks#1]
# Description

Remove the bullets in the navbar

<img width="697" alt="Screenshot 2023-10-16 at 14 42 55" src="https://github.com/pccoe-acm-hacktoberfest-2023/Starbucks/assets/62693272/ae88f779-e015-4530-b233-284f3abeb1fc">

**Comment by An-Array** [comment]
Can you assign me this issue? I would like to work on it. @ketan-sonar

**Comment by An-Array** [comment]
I am done resolving the issue and have sent pull request. @ketan-sonar

**Comment by Lubhavan-Burghate** [comment]
can you plz assign this to me.

**Comment by PrathameshTheurkar** [comment]
@Madhur155  I have assigned this issue to u , solve this issue and attach a screenshot , and also try to enhance the navbar .
