### ISSUE TITLE
bug: old twitter logo is used

### ISSUE THREAD

**Issue by baekusboo** [pccoe-acm-hacktoberfest-2023/Starbucks#14]
<img width="76" alt="image" src="https://github.com/pccoe-acm-hacktoberfest-2023/Starbucks/assets/83155556/efcd5274-580e-4d98-9bce-1e0926209a8a">

I would like to fix this issue by updating the twitter logo to the latest one. Kindly assign me this issue!

**Comment by mr-osiris** [comment]
i have replaced old logo with new logo.

**Comment by baekusboo** [comment]
@mr-osiris I want to take up this issue... @pccoe-acm kindly assign me and allow me to work on this issue under hacktoberfest!
