### ISSUE TITLE
[UI Upgrade]: Add favicon.ico

### ISSUE THREAD

**Issue by ketan-sonar** [pccoe-acm-hacktoberfest-2023/Starbucks#2]
# Description

The website should have a favicon.

**Comment by ghost** [comment]
can you assign me this task

**Comment by mr-osiris** [comment]
can you please assign this task to me because i have already created pr for this task.

**Comment by pranav-lad** [comment]
Hey @ketan-sonar, 
I would love to work on this issue. Kindly consider assigning it to me
here's my profile https://linktr.ee/pranavlad
