### ISSUE TITLE
Clicking Thumbnails Doesn't Load Images

### ISSUE THREAD

**Issue by PrathameshTheurkar** [pccoe-acm-hacktoberfest-2023/Starbucks#6]
**Description :** 

https://github.com/pccoe-acm-hacktoberfest-2023/Starbucks/assets/109230625/bf4b718b-ada1-46ba-ada2-975d07fce6c3

**Comment by Indrajeet-007** [comment]
can you please assign this issue to me.

**Comment by PrathameshTheurkar** [comment]
@Indra6969 I have assigned this issue to  u , feel free to raise a PR  and Good Luck !!

**Comment by PrathameshTheurkar** [comment]
@Indra6969 what's the progress ??

**Comment by PrathameshTheurkar** [comment]
Feel free to raise a PR , its on the first come first serve basis !!!

**Comment by AryanShriv** [comment]
Hello @PrathameshTheurkar can you assign this task to me?

**Comment by PrathameshTheurkar** [comment]
@AryanShriv  its on the first come first basis there is no need of assigning the issue , feel free to raise a PR .
